// Generated by scripts/generate-blur.mjs (pnpm blur). Do not edit by hand.
export const BLUR_DATA: Record<string, { src: string; ratio: number }> = {
  "PIC03277.webp": {
    "src": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYwCdMoQP6BMtK8OsFale4asAAP6z4+FH+FCcX/QKZx8ft5PkytS5ZfK1qTyLEbTji+C/l3lCuJXCbo6ezNOdRDUavec/TvHPFandQUBYRDAA",
    "ratio": 1.5
  },
  "PIC04257.webp": {
    "src": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoYABAAPu1mqk2ppaQiMAgBMB2JQBOgBDvTiS5KehdxtH81AADdNuAdCju5RiIL5qoXrscV9AUq3C6GTkjSELmeaKjCXKDG6vlvAYPj5y9Y0tXwXafF0rm/N5YCSQzz7d/NamAA",
    "ratio": 1.5001
  },
  "PIC03152.webp": {
    "src": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdACFZwjy+g1H7VmLwn2wVAAD+2EDZVySHQbZmXgS4rPsVCtpe5Ly2DIqEwMQVLKbbe92tc3IZxNK/49vjOFcCjYyzkjOy0/FIWnLEawN0GOgD3LsGY6wnX854CNoKVdi6q3rSHcc4l049IkRy8fTOJfdfRzL2eCrj+jWQWxMr7JFWC3HAO/oAAA==",
    "ratio": 1.5
  },
  "PIC03215.webp": {
    "src": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAAAwBgCdASoYACQAPu1mp02ppiOiMBVdUTAdiWcAyRAIONeCg/KegX/Nl7vlMOsPfs+Hkrv6DuzmF+jAAP7TldAQ3WcP07aPEsTnNvz6fLxwSU86TQMblUBsEshSBV6uvm3FXm64nVtEDea7uhv129JaWk84BJ5Dxg/OratsO78TBZmqfGIw1OMhIthCGyEggHsAAA==",
    "ratio": 0.6667
  },
  "PIC03308.webp": {
    "src": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAADQBQCdASoYACQAPu1ep02ppKOiNVQMATAdiWUAy6QLNluOCxynx3pC/dwSSXReIKz8msrx++wAAP3G8/NzbNRl3q07Mr+KX4UMaNfRqefOWVKOWL2dxgPuazfJM7z87jeGIhWirlTMwcYwMVEE7HIMHRaVjLk19CC2SbRTEUKM3P204mZcgjkF0lMYhejx1ucg5Fqj4wYKj9bFQWa6XBTZuICxbTPj5XYQTJpozruvTP4+0wnh9LRZt3BJYAAA",
    "ratio": 0.6667
  },
  "PIC03122.webp": {
    "src": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JQBbZA81l266CYQs5QAD9IPMzSi81rF/Rm+9O8CAG8SNPuenuodSq7s5Y1SO0EP2CAAAA",
    "ratio": 1.5
  },
  "PIC02099.webp": {
    "src": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JQBYdhFiuiGAhblEUNsgA/uJPnHb8ftoGQubXtYCsGzzDZkxFUUgQrIphAZySNQ8mzpT+t1GtXjz1eRJ1rhjABWF82E+gYU8VZHoFEYlw4sr3w2X+J0QdIkDwxQcUR1D92HbmRLGMjK+dXBYYs1zHm0F2D49DlQKSFEAV5k/M3t23AHEAAA==",
    "ratio": 1.5002
  },
  "PIC02406-Pano.webp": {
    "src": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoYAAkAPu1iqU2ppaOiMAgBMB2JQBOgA26eH84Ani2AAAD+dMH1rKMBqJ+pEbXVooMt35ebqIJSBWLpD1GA2FuQZzY6d+6zmctk73wxz8rubmuVco9M3fQA",
    "ratio": 2.5672
  },
  "PIC02307-Pano.webp": {
    "src": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBACdASoYAA4APu1qrU8ppiQiMAgBMB2JQBOmUGYwBO7+RpJRwUx5uQAA/p7pjMzHkKtggRfz3o0f6lqD9IQ1Ppdkt0TdAIw02aM+I1PsytwFugzYewjj7c4hKetHZcT4ybqxq1hTMtbxZFrd0gfS+0+YMpMLY40xmJF8AAA=",
    "ratio": 1.7777
  }
}
