// Generates app/lib/blurData.ts: a ~24px WebP data URI plus aspect ratio per photo, keyed by the
// photo slug (basename of `url`). Run `pnpm blur` after adding photos. Images are downloaded
// into memory only; nothing but the resulting text file is written.
import { writeFile } from "node:fs/promises"
import sharp from "sharp"

import { photos } from "../app/constants.ts"

/** Same rule as `slugFromPhotoUrl` in app/lib/photoSlug.ts (not imported: it uses extensionless paths). */
const slugFromPhotoUrl = (url) => decodeURIComponent(new URL(url).pathname.split("/").filter(Boolean).pop() ?? "")

const TINY_WIDTH = 24
const OUT = new URL("../app/lib/blurData.ts", import.meta.url)

const entries = {}
for (const photo of Object.values(photos).flat()) {
  const slug = slugFromPhotoUrl(photo.url)
  // The smaller asset is enough for a 24px preview and downloads faster.
  const res = await fetch(photo.urlLowQuality)
  if (!res.ok) throw new Error(`${res.status} fetching ${photo.urlLowQuality}`)
  const input = Buffer.from(await res.arrayBuffer())

  const { width, height, orientation = 1 } = await sharp(input).metadata()
  const swap = orientation >= 5
  const ratio = (swap ? height / width : width / height).toFixed(4)

  const tiny = await sharp(input)
    .rotate()
    .resize({ width: TINY_WIDTH })
    .webp({ quality: 40 })
    .toBuffer()

  entries[slug] = { src: `data:image/webp;base64,${tiny.toString("base64")}`, ratio: Number(ratio) }
  console.log(`${slug}: ${tiny.length} bytes, ratio ${ratio}`)
}

const body = `// Generated by scripts/generate-blur.mjs (pnpm blur). Do not edit by hand.
export const BLUR_DATA: Record<string, { src: string; ratio: number }> = ${JSON.stringify(entries, null, 2)}
`
await writeFile(OUT, body)
console.log(`Wrote ${Object.keys(entries).length} entries`)
